import os
import litellm

if not os.getenv("GROQ_API_KEY"):
    raise ValueError("CRITICAL: GROQ_API_KEY environment variable not found.")

try:
    import crewai.llms.cache as _crewai_cache
    _crewai_cache.mark_cache_breakpoint = lambda msg: msg
except ImportError:
    pass

from crewai import Crew, Process
from agents.restaurant_agents import RestaurantAgents
from agents.customer_agent import CustomerSystem
from tasks.restaurant_tasks import RestaurantTasks

def run_simulation():
    print(f"\n--- STARTING FULLY AUTONOMOUS RESTAURANT SIMULATION ---")

    # Initialize agents
    rest_agents = RestaurantAgents()
    seating_mgr = rest_agents.seating_manager()
    waiter = rest_agents.waiter()
    chef = rest_agents.sushi_chef()
    
    # Completely empty instantiation - data is generated by the model at runtime
    customer = CustomerSystem().customer_agent()

    # Initialize task pipeline
    tasks = RestaurantTasks()
    t1 = tasks.customer_arrival_task(customer)
    t2 = tasks.seat_customer_task(seating_mgr, t1)
    t3 = tasks.customer_order_task(customer, t2)
    t4 = tasks.kitchen_allergy_check_task(chef, t1, t3)
    t5 = tasks.customer_decision_task(customer, t4)
    t6 = tasks.finalize_cooking_task(chef, t5)

    restaurant_crew = Crew(
        agents=[customer, seating_mgr, waiter, chef],
        tasks=[t1, t2, t3, t4, t5, t6],
        process=Process.sequential
    )

    result = restaurant_crew.kickoff()
    print("\n--- FINAL SIMULATION RESULT ---")
    print(result)

if __name__ == "__main__":
    run_simulation()