from crewai import Agent, LLM
from seating_system.seating_tools import check_seat_availability, assign_seat
from order_system.order_tools import check_allergens
from kitchen_system.kitchen_tools import process_order_stock

groq_llm = LLM(
    model="groq/llama-3.3-70b-versatile",
    temperature=0.0
)

class RestaurantAgents:
    def seating_manager(self):
        return Agent(
            role="Seating Manager",
            goal="Seat arriving groups instantly using 1 sentence.",
            backstory="Host at Kalye West. You extract the group size, run your tools once, and output the table assignment.",
            tools=[check_seat_availability, assign_seat],
            verbose=True,
            allow_delegation=False,
            max_iter=3,
            llm=groq_llm
        )

    def waiter(self):
        return Agent(
            role="Waiter",
            goal="Validate allergen safety using exactly 1 sentence.",
            backstory="Sushi waiter. You take the chosen dish and allergy, check them with your tool, and output a 1-sentence verdict.",
            tools=[check_allergens],
            verbose=True,
            allow_delegation=False,
            max_iter=3,
            llm=groq_llm
        )

    def sushi_chef(self):
        return Agent(
            role="Sushi Chef",
            goal="Process the stock updates and cook safe food based strictly on tool responses.",
            backstory=(
                "You are the Itamae. You execute your 'Check and Update Stock' tool exactly once per task. "
                "CRITICAL: You must never invent or assume an order is ready if the tool returns a Kitchen Error. "
                "Your final answer must match the exact confirmation text generated by your database tool."
            ),
            tools=[process_order_stock],
            verbose=True,
            allow_delegation=False,
            max_iter=3,
            llm=groq_llm
        )