from crewai import Agent, LLM
from order_system.order_tools import view_restaurant_menu, check_menu_and_allergens, save_order, check_order_status
from kitchen_system.kitchen_tools import process_order_stock

groq_llm = LLM(
    model="groq/llama-3.3-70b-versatile",
    temperature=0.0
)

class RestaurantAgents:
    def waiter(self):
        return Agent(
            role="Waiter",
            goal="Validate customer orders, check menu availability, check allergies, save accepted orders, and reject unsafe orders.",
            backstory=(
                "You are a careful restaurant waiter. Your job is to protect customers from allergens, "
                "make sure dishes exist on the menu, and record only valid customer orders."
            ),
            tools=[view_restaurant_menu, check_menu_and_allergens, save_order, check_order_status],
            verbose=True,
            allow_delegation=True,
            llm="groq/llama-3.3-70b-versatile"
        )

    def sushi_chef(self):
        return Agent(
            role="Sushi Chef",
            goal="Process the stock updates and cook safe food based strictly on tool responses.",
            backstory=(
                "You are the Itamae. You execute your 'Check and Update Stock' tool exactly once per task. "
                "CRITICAL: You must never invent or assume an order is ready if the tool returns a Kitchen Error. "
                "Your final answer must match the exact confirmation text generated by your database tool."
            ),
            tools=[process_order_stock],
            verbose=True,
            allow_delegation=False,
            max_iter=3,
            llm=groq_llm
        )
